### ISSUE TITLE
Readme title shoud say:Angular2-markdown-app not Angular2 Starterkit

### ISSUE THREAD

**Issue by HansS** [AntJanus/angular2-markdown-app#2]
Maybe a copy paste error!

**Comment by AntJanus** [comment]
whoops! Thanks! I used the starter kit to build this app!

**Comment by HansS** [comment]
Keep on with your Blog and Github, it is content from which everybody can lean!
regardsHans

Date: Thu, 17 Dec 2015 10:16:40 -0800

**Comment by AntJanus** [comment]
readme updated
